### ISSUE TITLE
add links to images in list-circles

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/reconhub.github.io#1]
A comment that's been made several time: would be really cool to add optional links to the images in `list-circles`. 

For instance, from [resources.md](https://raw.githubusercontent.com/reconhub/reconhub.github.io/master/resources.md):

```
 tutorials-list:
  - name: Phylogenetics using R
    img: /img/tutorials/green.png
    url:  https://github.com/reconhub/phylo-practical
    desc: Overview of phylogenetics in R using seasonal influenza sequences.
    github: https://github.com/reconhub/phylo-practical
```

@daattali is it easy to add?
